<template>
  <div class="heading text-center font-poppins text-2xl m-5 text-gray-900">
    Selecione o sabor favorito!
  </div>

  <div
    class="
      holder
      mx-auto
      w-10/12
      grid
      sm:grid-cols-1
      md:grid-cols-3
      lg:grid-cols-4
    "
  >
    <div class="each mb-10 m-2 shadow-lg border-gray-800 bg-gray-100 relative">
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-xs
          flex
          p-1
          font-semibold
          text-gray-500
          bg-gray-300
          justify-center
        "
      >
        Calabresa
      </div>
      <button
        class="
          mt-2
          mb-2
          ml-2
          mr-2
          bg-gray-700
          hover:bg-gray-800
          text-white
          font-bold
          py-1
          px-2
          rounded
          justify-center
        "
      >
        -
      </button>
      0
      <button
        class="
          mt-2
          mb-2
          ml-2
          bg-gray-700
          hover:bg-gray-800
          text-white
          font-bold
          py-1
          px-2
          rounded
        "
      >
        +
      </button>
      <p class="bg-gray-100 circle-lg flex center justify-center">$55</p>
    </div>
    <div class="each mb-10 m-2 shadow-lg border-gray-800 bg-gray-100 relative">
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-xs
          flex
          p-1
          font-semibold
          text-gray-500
          bg-gray-300
        "
      >
        Calabresa
      </div>
    </div>
    <div class="each mb-10 m-2 shadow-lg border-gray-800 bg-gray-100 relative">
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-xs
          flex
          p-1
          font-semibold
          text-gray-500
          bg-gray-300
        "
      >
        Calabresa
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>