<template>
  <div class="heading text-center font-poppins text-2xl m-5 text-gray-900">
    Selecione o sabor favorito!
  </div>

  <div
    class="
      holder
      mx-auto
      w-10/12
      grid
      sm:grid-cols-1
      md:grid-cols-3
      lg:grid-cols-3
    "
  >
    <div
      class="
        each
        mb-10
        m-2
        shadow-lg
        border-gray-800
        bg-gray-100
        relative
        transition
        duration-500
        ease-in-out
        transform
        hover:-translate-y-1 hover:scale-110
      "
    >
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-md
          font-poppins
          flex
          p-1
          font-semibold
          text-gray-500
          ml-2
        "
      >
        Calabresa
      </div>
      <div>
        <button
          class="
            mt-2
            mb-2
            ml-2
            mr-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
            justify-center
          "
        >
          +
        </button>
        0
        <button
          class="
            mt-2
            mb-2
            ml-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
          "
        >
          -
        </button>
        <p class="bg-gray-100 circle-lg flex ml-2">$55</p>
      </div>
    </div>
    <div
      class="
        each
        mb-10
        m-2
        shadow-lg
        border-gray-800
        bg-gray-100
        relative
        transition
        duration-500
        ease-in-out
        transform
        hover:-translate-y-1 hover:scale-110
      "
    >
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-md
          font-poppins
          flex
          p-1
          font-semibold
          text-gray-500
          ml-2
        "
      >
        Calabresa
      </div>
      <div>
        <button
          class="
            mt-2
            mb-2
            ml-2
            mr-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
            justify-center
          "
        >
          +
        </button>
        0
        <button
          class="
            mt-2
            mb-2
            ml-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
          "
        >
          -
        </button>
        <p class="bg-gray-100 circle-lg flex ml-2">$55</p>
      </div>
    </div>
    <div
      class="
        each
        mb-10
        m-2
        shadow-lg
        border-gray-800
        bg-gray-100
        relative
        transition
        duration-500
        ease-in-out
        transform
        hover:-translate-y-1 hover:scale-110
      "
    >
      <img
        class="w-full"
        src="https://media.istockphoto.com/photos/delicious-vegetarian-pizza-on-white-picture-id1192094401?k=20&m=1192094401&s=612x612&w=0&h=jesvXuPyvqM36GQ5QEvJrL3QZjK6YKsziUUF3ZbW0gw="
        alt=""
      />
      <div
        class="
          info-box
          text-md
          font-poppins
          flex
          p-1
          font-semibold
          text-gray-500
          ml-2
        "
      >
        Calabresa
      </div>

      <div>
        <button
          class="
            mt-2
            mb-2
            ml-2
            mr-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
            justify-center
          "
        >
          +
        </button>
        0
        <button
          class="
            mt-2
            mb-2
            ml-2
            bg-gray-700
            hover:bg-gray-800
            text-white
            font-bold
            py-1
            px-2
            rounded
          "
        >
          -
        </button>
        <p class="bg-gray-100 circle-lg flex ml-2">$55</p>
      </div>
    </div>
  </div>
  <div
    class="
      holder
      mx-auto
      w-10/12
      grid
      sm:grid-cols-1
      md:grid-cols-3
      lg:grid-cols-1
      shadow-2xl
    "
  >
    <h1
      class="
        flex
        justify-center
        mb-8
        rounded-lg
        text-2xl
        font-poppins
        text-gray-900
      "
    >
      Carrinho vazio!!!
    </h1>
    <hr />

    <div>
      <h2
        class="
          info-box
          text-md
          font-poppins
          flex
          justify-center
          p-1
          font-semibold
          text-gray-500
          ml-2
        "
      >
        Calabresa
      </h2>
      <p class="flex justify-center">Total $ 58</p>
      <div class="flex justify-center mb-12 mt-4">
        <button
          class="
            bg-green-600
            px-2
            py-2
            hover:bg-green-700
            rounded
            mr-2
            font-poppins
          "
        >
          Finalizar
        </button>
        <button
          class="bg-red-600 px-2 py-2 hover:bg-red-700 rounded font-poppins"
        >
          Cancelar
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>